name: monad-persist
version: 0.0.2.0
category: Database
synopsis: An mtl-style typeclass and transformer for persistent.
description: An mtl-style typeclass and transformer for persistent.
author: Alexis King <lexi.lambda@gmail.com>
maintainer: Alexis King <lexi.lambda@gmail.com>
copyright: 2017 CJ Affiliate by Conversant
github: cjdev/monad-persist

license: ISC
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base >= 4.8 && < 5
  - exceptions >= 0.6
  - monad-control >= 1.0.0.0 && < 2
  - monad-logger >= 0.3.10
  - mtl
  - persistent >= 2.5 && < 3
  - text
  - transformers
  - transformers-base
  - unliftio-core
  source-dirs: library

tests:
  monad-persist-test-suite:
    dependencies:
    - base
    - hspec
    - monad-control
    - monad-logger
    - monad-persist
    - persistent
    - persistent-sqlite
    - persistent-template
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
